# Generated by Django 4.0.1 on 2022-01-21 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suyoapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propietario',
            options={'ordering': ['nombres']},
        ),
        migrations.RemoveField(
            model_name='predio',
            name='coordenadas',
        ),
        migrations.AddField(
            model_name='predio',
            name='latidud',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='predio',
            name='longitud',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='predio',
            name='direccion',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.DeleteModel(
            name='Coordenada',
        ),
    ]
