# Generated by Django 4.0.1 on 2022-01-22 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suyoapi', '0003_alter_predio_latidud_alter_predio_longitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predio',
            name='latidud',
            field=models.DecimalField(decimal_places=10, max_digits=19),
        ),
        migrations.AlterField(
            model_name='predio',
            name='longitud',
            field=models.DecimalField(decimal_places=10, max_digits=19),
        ),
    ]
